package com.tyron.compiler;

import com.apk.builder.ApplicationLoader;
import com.apk.builder.BinaryExecutor;
import com.apk.builder.logger.Logger;
import com.apk.builder.model.Project;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class AAPT2Compiler extends Compiler {

    public AAPT2Compiler(Project project) {
        super(project);
    }

    @Override
    public void run() throws Exception {
        notifyProgress("[AAPT2] Initializing resource compiler...", 1, 7);

        File aapt2Binary = ApplicationLoader.getInstance().getAAPT2Binary();
        if (!aapt2Binary.exists()) {
            throw new IllegalStateException("AAPT2 binary not found: " + aapt2Binary.getAbsolutePath());
        }
        aapt2Binary.setExecutable(true, false);

        File androidJar = ApplicationLoader.getInstance().getAndroidJar(project.getTargetSdk());
        if (!androidJar.exists() || androidJar.length() == 0) {
            throw new IllegalStateException("android.jar platform framework not found at: " + androidJar.getAbsolutePath());
        }

        File buildDir = project.getBuildDir();
        File compiledResDir = new File(buildDir, "compiled_res");
        File genDir = new File(buildDir, "gen");
        File binDir = project.getBinDir();

        deleteDirectory(compiledResDir);
        deleteDirectory(genDir);
        compiledResDir.mkdirs();
        genDir.mkdirs();
        binDir.mkdirs();

        // Step 1: AAPT2 Compile
        notifyProgress("[AAPT2] Compiling XML resources and assets...", 1, 7);
        Logger.log("[AAPT2] Compiling XML resources from " + project.getResDir().getAbsolutePath());

        List<String> compileCmd = new ArrayList<>();
        compileCmd.add(aapt2Binary.getAbsolutePath());
        compileCmd.add("compile");
        compileCmd.add("--dir");
        compileCmd.add(project.getResDir().getAbsolutePath());
        compileCmd.add("-o");
        compileCmd.add(compiledResDir.getAbsolutePath());

        BinaryExecutor.Result compileResult = BinaryExecutor.execute(compileCmd, project.getResDir());
        if (!compileResult.isSuccess()) {
            throw new Exception("AAPT2 compile failed:
" + compileResult.output);
        }

        File[] flatFiles = compiledResDir.listFiles((dir, name) -> name.endsWith(".flat"));
        if (flatFiles == null || flatFiles.length == 0) {
            throw new Exception("No .flat files generated by AAPT2 compile in " + compiledResDir.getAbsolutePath());
        }
        Logger.log("[AAPT2] Compiled " + flatFiles.length + " resource files successfully.");

        // Step 2: AAPT2 Link
        notifyProgress("[AAPT2] Compiling XML resources and assets into resources.ap_...", 1, 7);
        File resourcesAp = new File(binDir, "resources.ap_");

        List<String> linkCmd = new ArrayList<>();
        linkCmd.add(aapt2Binary.getAbsolutePath());
        linkCmd.add("link");
        linkCmd.add("-I");
        linkCmd.add(androidJar.getAbsolutePath());
        linkCmd.add("--manifest");
        linkCmd.add(project.getManifestFile().getAbsolutePath());
        linkCmd.add("--java");
        linkCmd.add(genDir.getAbsolutePath());
        linkCmd.add("-o");
        linkCmd.add(resourcesAp.getAbsolutePath());
        linkCmd.add("--auto-add-overlay");
        linkCmd.add("--min-sdk-version");
        linkCmd.add(String.valueOf(project.getMinSdk()));
        linkCmd.add("--target-sdk-version");
        linkCmd.add(String.valueOf(project.getTargetSdk()));
        linkCmd.add("--version-code");
        linkCmd.add(String.valueOf(project.getVersionCode()));
        linkCmd.add("--version-name");
        linkCmd.add(project.getVersionName());

        // Assets directory if present
        File assetsDir = new File(project.getRootPath(), "app/src/main/assets");
        if (!assetsDir.exists()) assetsDir = new File(project.getRootPath(), "src/main/assets");
        if (assetsDir.exists() && assetsDir.isDirectory()) {
            linkCmd.add("-A");
            linkCmd.add(assetsDir.getAbsolutePath());
        }

        for (File flat : flatFiles) {
            linkCmd.add("-R");
            linkCmd.add(flat.getAbsolutePath());
        }

        BinaryExecutor.Result linkResult = BinaryExecutor.execute(linkCmd, buildDir);
        if (!linkResult.isSuccess()) {
            throw new Exception("AAPT2 link failed:
" + linkResult.output);
        }

        if (!resourcesAp.exists() || resourcesAp.length() == 0) {
            throw new Exception("AAPT2 link completed but resources.ap_ was not created!");
        }

        Logger.log("[AAPT2] Generated resources.ap_ (" + resourcesAp.length() + " bytes) and R.java.");
    }

    private void deleteDirectory(File dir) {
        if (!dir.exists()) return;
        File[] files = dir.listFiles();
        if (files != null) {
            for (File f : files) {
                if (f.isDirectory()) deleteDirectory(f);
                else f.delete();
            }
        }
        dir.delete();
    }
}
